### PR TITLE
Explicit permission escalation is now needed for a push

### PR DESCRIPTION
**Pull request by arran4**
Basically you now must denote that you want the action to have write:
```
    permissions:
      contents: write
```

I have no idea where this is documented but I found it from another action.

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I just tested it and it seems to work for me without it.

The action uses [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to push the changes and their examples don't require this either.

**Comment by arran4** [comment]
Perhaps it's legacied in? It didn't work for me until I added it.. Maybe leave this open just incase?

**Comment by DenverCoder1** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions

https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

Based on these links, it seems to me that it will by default allow writing (unless it's a pull request from a fork), but if you set any permissions explicitly, then everything else will have no access.

**Comment by arran4** [comment]
Ah.. Makes sense I am doing the work from PRs. :P

**Pull request closed without merging**
